function xlsxXmlEscape(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")}
function xlsxUtf8(str){return new TextEncoder().encode(String(str))}
function xlsxU16(n){const a=new Uint8Array(2);new DataView(a.buffer).setUint16(0,n,true);return a}
function xlsxU32(n){const a=new Uint8Array(4);new DataView(a.buffer).setUint32(0,n>>>0,true);return a}
function xlsxConcat(parts){const len=parts.reduce((a,p)=>a+p.length,0),out=new Uint8Array(len);let off=0;parts.forEach(p=>{out.set(p,off);off+=p.length});return out}
let XLSX_CRC_TABLE=null;
function xlsxCrc32(bytes){if(!XLSX_CRC_TABLE){XLSX_CRC_TABLE=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xEDB88320^(c>>>1)):(c>>>1);XLSX_CRC_TABLE[n]=c>>>0}}let crc=0xFFFFFFFF;for(let i=0;i<bytes.length;i++)crc=XLSX_CRC_TABLE[(crc^bytes[i])&0xFF]^(crc>>>8);return(crc^0xFFFFFFFF)>>>0}
function xlsxZipStore(files){const localParts=[],centralParts=[];let offset=0;files.forEach(file=>{const nameBytes=xlsxUtf8(file.name),dataBytes=file.data instanceof Uint8Array?file.data:xlsxUtf8(file.data),crc=xlsxCrc32(dataBytes);const localHeader=xlsxConcat([xlsxU32(0x04034b50),xlsxU16(20),xlsxU16(0),xlsxU16(0),xlsxU16(0),xlsxU16(0),xlsxU32(crc),xlsxU32(dataBytes.length),xlsxU32(dataBytes.length),xlsxU16(nameBytes.length),xlsxU16(0)]);localParts.push(localHeader,nameBytes,dataBytes);const centralHeader=xlsxConcat([xlsxU32(0x02014b50),xlsxU16(20),xlsxU16(20),xlsxU16(0),xlsxU16(0),xlsxU16(0),xlsxU16(0),xlsxU32(crc),xlsxU32(dataBytes.length),xlsxU32(dataBytes.length),xlsxU16(nameBytes.length),xlsxU16(0),xlsxU16(0),xlsxU16(0),xlsxU16(0),xlsxU32(0),xlsxU32(offset)]);centralParts.push(centralHeader,nameBytes);offset+=localHeader.length+nameBytes.length+dataBytes.length});const central=xlsxConcat(centralParts),end=xlsxConcat([xlsxU32(0x06054b50),xlsxU16(0),xlsxU16(0),xlsxU16(files.length),xlsxU16(files.length),xlsxU32(central.length),xlsxU32(offset),xlsxU16(0)]);return xlsxConcat([...localParts,central,end])}
function xlsxColumnName(index){let n=index+1,s="";while(n>0){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s}
function xlsxCell(ref,value,style=0,type=null){if(value===null||value===undefined||value==="")return`<c r="${ref}" s="${style}"/>`;if(type==="n"||(type===null&&typeof value==="number"&&Number.isFinite(value)))return`<c r="${ref}" s="${style}"><v>${Number(value)}</v></c>`;return`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xlsxXmlEscape(value)}</t></is></c>`}
function xlsxSheetXml(rows,widths=[],merges=[]){const rowXml=rows.map((row,ri)=>{const cells=row.map((cell,ci)=>{if(cell===null||cell===undefined)return"";const obj=(typeof cell==="object"&&!Array.isArray(cell)&&"v" in cell)?cell:{v:cell};const ref=xlsxColumnName(ci)+(ri+1);return xlsxCell(ref,obj.v,obj.s||0,obj.t||null)}).join("");return`<row r="${ri+1}">${cells}</row>`}).join("");const cols=widths.length?`<cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join("")}</cols>`:"";const mergeXml=merges.length?`<mergeCells count="${merges.length}">${merges.map(m=>`<mergeCell ref="${m}"/>`).join("")}</mergeCells>`:"";return`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">${cols}<sheetData>${rowXml}</sheetData>${mergeXml}</worksheet>`}
