const BASE_MENU = {"Entradas, saladas e frios": ["Focaccia", "Mix de folhas", "Folhas escuras", "Tomate assado", "Tomate em rodelas", "Batata bolinha assada", "Cenoura ralada", "Beterraba ralada", "Pepino em rodelas", "Risone", "Salada de banana", "Vinagrete de abacaxi", "Hommus", "Babaganoush", "Picles de maxixe", "Picles de cebola", "Picles de rabanete", "Tabule"], "Guarnições e pratos quentes": ["Arroz branco", "Arroz 7 cereais", "Tutu", "Feijão tropeiro", "Feijão preto", "Angu", "Couve", "Quibebe", "Farofa de ovos", "Lasanha napolitana", "Couve-flor gratinada", "Penne", "Molho de tomate", "Molho pesto", "Molho de queijo", "Estrogonofe de cogumelos"], "Proteínas": ["Mix suíno", "Linguiça", "Lagarto", "Estrogonofe de frango"], "Sobremesas": ["Pudim", "Manjar", "Salame de chocolate", "Goiabada", "Queijo", "Cocada", "Pé de moleque", "Doce de figo", "Doce de leite", "Mix de frutas", "Brigadeiro de milho", "Brigadeiro de capim", "Banoffe", "Doce de abóbora", "Crumble de maçã", "Crumble de banana", "Arroz doce"]};
const DEFAULT_DAILY = ["Arroz branco", "Arroz 7 cereais", "Feijão preto", "Tutu", "Feijão tropeiro", "Angu", "Couve", "Farofa de ovos", "Penne", "Molho de tomate", "Molho de queijo", "Molho pesto", "Quibebe", "Lasanha napolitana", "Linguiça", "Mix suíno", "Focaccia", "Mix de folhas", "Folhas escuras", "Tomate assado", "Tomate em rodelas", "Batata bolinha assada", "Cenoura ralada", "Beterraba ralada", "Pepino em rodelas", "Risone", "Salada de banana", "Vinagrete de abacaxi", "Hommus", "Babaganoush", "Picles de maxixe", "Picles de cebola", "Picles de rabanete"];
const TRAYS = [{"name": "Frigideira", "weight": 3.216}, {"name": "Panela oval", "weight": 4.904}, {"name": "Retângula Lasanha", "weight": 5.998}, {"name": "Arroz Panela", "weight": 5.778}, {"name": "Redonda Lisa", "weight": 4.138}, {"name": "Grande Redonda", "weight": 6.285}, {"name": "Frigideira Grande", "weight": 3.578}, {"name": "Assadeira Grande", "weight": 4.192}, {"name": "Redonda Molho", "weight": 2.254}, {"name": "Panela oval Grande", "weight": 7.225}, {"name": "Baixa", "weight": 3.89}];

const KEY_USERS="pp_users_v1";
const KEY_MANUAL="pp_manual_dishes_v1";
const KEY_SESSION="pp_session_v1";
let session=null;
let state=null;

function safeGet(key, sessionStore=false){try{return (sessionStore?sessionStorage:localStorage).getItem(key)}catch(e){return null}}
function safeSet(key,val, sessionStore=false){try{(sessionStore?sessionStorage:localStorage).setItem(key,val)}catch(e){}}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function dayKey(){return "pp_day_"+today()}
function defaultUsers(){return [{name:"Administrador",username:"adm",password:"1234",role:"admin",active:true},{name:"Operador",username:"operador",password:"1234",role:"user",active:true}]}
function getUsers(){let u=[];try{u=JSON.parse(safeGet(KEY_USERS)||"[]")}catch(e){u=[]}if(!Array.isArray(u))u=[];let adm=u.find(x=>String(x.username||"").toLowerCase()==="adm");if(!adm){adm={name:"Administrador",username:"adm",password:"1234",role:"admin",active:true};u.unshift(adm)}else{adm.name=adm.name||"Administrador";adm.username="adm";adm.password=adm.password||"1234";adm.role="admin";adm.active=true}let operador=u.find(x=>String(x.username||"").toLowerCase()==="operador");if(!operador){u.push({name:"Operador",username:"operador",password:"1234",role:"user",active:true})}safeSet(KEY_USERS,JSON.stringify(u));return u}
function setUsers(u){safeSet(KEY_USERS,JSON.stringify(u))}
function getManual(){try{const a=JSON.parse(safeGet(KEY_MANUAL)||"[]");return Array.isArray(a)?a:[]}catch(e){return []}}
function setManual(a){safeSet(KEY_MANUAL,JSON.stringify(a))}
function buildMenu(){const m=JSON.parse(JSON.stringify(BASE_MENU));getManual().forEach(x=>{const cat=x.category||"Outros";if(!m[cat])m[cat]=[];if(!m[cat].some(n=>n.toLowerCase()===String(x.name).toLowerCase()))m[cat].push(x.name)});getAdminDishes().forEach(x=>{const cat=x.category||"Outros";if(!m[cat])m[cat]=[];if(!m[cat].some(n=>n.toLowerCase()===String(x.name).toLowerCase()))m[cat].push(x.name)});return m}
function createDay(){const items={};DEFAULT_DAILY.forEach(n=>items[n]={gross:0,trayName:"",trayWeight:0,repos:[],finalGross:0});return {date:today(),selected:[...DEFAULT_DAILY],items}}
function loadDay(){let d=null;try{d=JSON.parse(safeGet(dayKey())||"null")}catch(e){d=null}if(!d||d.date!==today()) d=createDay();if(!Array.isArray(d.selected)) d.selected=[];if(!d.items||typeof d.items!=="object") d.items={};state=d;state.selected.forEach(ensureItemOn);saveDay()}
function saveDay(){safeSet(dayKey(),JSON.stringify(state))}
function ensureItemOn(name){if(!state.items[name])state.items[name]={gross:0,trayName:"",trayWeight:0,repos:[],finalGross:0};const d=state.items[name];if(!Array.isArray(d.repos))d.repos=[];d.gross=Number(d.gross||0);d.trayWeight=Number(d.trayWeight||0);d.finalGross=Number(d.finalGross||0)}
function orderedSelected(){const m=buildMenu(), set=new Set(state.selected), out=[];Object.entries(m).forEach(([cat,items])=>items.forEach(name=>{if(set.has(name))out.push(name)}));state.selected.forEach(name=>{if(!out.includes(name))out.push(name)});return out}
function trayByName(name){return allTrayPresets().find(t=>t.name===name)||null}
function initialNet(name){const d=state.items[name];return Math.max(0,Number(d.gross||0)-Number(d.trayWeight||0))}
function repoTotal(name){return (state.items[name].repos||[]).reduce((a,r)=>a+Number(r.weight||0),0)}
function finalNet(name){const d=state.items[name];return Math.max(0,Number(d.finalGross||0)-Number(d.trayWeight||0))}
function nowTime(){const d=new Date();return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}
function safeId(s){return "x_"+btoa(unescape(encodeURIComponent(s))).replace(/[^a-zA-Z0-9]/g,"")}
function login(){const un=document.getElementById("loginUser").value.trim().toLowerCase();const pw=document.getElementById("loginPass").value;const msg=document.getElementById("loginMsg");const u=getUsers().find(x=>String(x.username||"").toLowerCase()===un&&String(x.password||"")===pw);if(!u){msg.textContent="Usuário ou senha inválidos.";return}if(u.active===false){msg.textContent="Acesso bloqueado pelo administrador.";return}session={name:u.name,username:u.username,role:u.role};safeSet(KEY_SESSION,JSON.stringify(session),true);msg.textContent="";openApp()}
function openApp(){if(!session)return;document.getElementById("authScreen").classList.add("hidden");document.getElementById("mainApp").classList.remove("hidden");document.getElementById("loggedUser").textContent=`${session.name} (${session.username})`;document.getElementById("adminButton").classList.add("hidden");const saasUser=document.getElementById("saasLoggedUser");if(saasUser) saasUser.textContent=`${session.name} (${session.username})`;const adminNav=document.getElementById("adminNavButton");if(adminNav) adminNav.classList.toggle("hidden",session.role!=="admin");loadDay();renderMenu();const categories=document.getElementById("categories");if(categories && !categories.children.length){renderMenu()}go(1)}
function logout(){safeSet(KEY_SESSION,"",true);session=null;location.reload()}
function renderMenu(){const root=document.getElementById("categories");if(!root) return;const m=buildMenu();const manuals=[...getManual(),...getAdminDishes()];root.innerHTML="";Object.entries(m).forEach(([cat,items])=>{const box=document.createElement("div");box.className="category";box.innerHTML=`<div class="cat-head"><b>${cat}</b><span class="count">${items.length} itens</span><button class="btn" data-cat="${cat}">Selecionar categoria</button></div><div class="items"></div>`;const grid=box.querySelector(".items");items.forEach(name=>{const label=document.createElement("label");label.className="item";const checked=state.selected.includes(name);const isDefault=DEFAULT_DAILY.includes(name);const isManual=manuals.some(x=>x.name===name);label.innerHTML=`<input type="checkbox" data-dish="${name.replace(/"/g,"&quot;")}" ${checked?"checked":""}><span>${name}</span>${isDefault?'<span class="tag">Padrão</span>':""}${isManual?'<span class="tag manual-tag">Salvo</span>':""}`;label.querySelector("input").addEventListener("change",e=>toggleDish(name,e.target.checked));grid.appendChild(label)});box.querySelector("[data-cat]").addEventListener("click",()=>toggleCategory(cat));root.appendChild(box)});document.getElementById("selectedCount").textContent=state.selected.length}
function toggleDish(name,on){if(on&&!state.selected.includes(name))state.selected.push(name);if(!on)state.selected=state.selected.filter(x=>x!==name);if(on)ensureItemOn(name);saveDay();document.getElementById("selectedCount").textContent=state.selected.length}
function toggleCategory(cat){const items=buildMenu()[cat]||[], all=items.every(n=>state.selected.includes(n));if(all)state.selected=state.selected.filter(n=>!items.includes(n));else items.forEach(n=>{if(!state.selected.includes(n))state.selected.push(n);ensureItemOn(n)});saveDay();renderMenu()}
function clearMenu(){state.selected=[];saveDay();renderMenu()}
function addManual(){const name=document.getElementById("manualDishName").value.trim();const category=document.getElementById("manualDishCategory").value;const msg=document.getElementById("manualMsg");if(!name){msg.textContent="Informe o nome do prato.";return}const exists=Object.values(buildMenu()).flat().some(n=>n.toLowerCase()===name.toLowerCase());if(exists){msg.textContent="Este prato já existe na lista.";return}const a=getManual();a.push({name,category});setManual(a);state.selected.push(name);ensureItemOn(name);saveDay();document.getElementById("manualDishName").value="";msg.style.color="var(--green)";msg.textContent="Prato salvo e selecionado para hoje.";renderMenu()}
function updateSaaSNav(n){const titles={1:["Cardápio do Dia","Selecione os pratos que estão no buffet"],2:["Pesos Iniciais","Informe peso e travessa de cada prato"],3:["Reposição do Buffet","Inclua rapidamente os pesos das reposições"],4:["Fechamento","Registre os pesos finais do buffet"],5:["Resumo do Dia","Acompanhe consumo e perdas"],6:["Histórico","Consulte resultados por dia e exporte para Excel"],7:["Administração","Usuários, pratos, travessas e controles gerais"]};document.querySelectorAll("[data-saas-go]").forEach(btn=>{btn.classList.toggle("active",Number(btn.dataset.saasGo)===n)});const data=titles[n]||titles[1];const title=document.getElementById("saasPageTitle");const sub=document.getElementById("saasPageSubtitle");if(title) title.textContent=data[0];if(sub) sub.textContent=data[1];document.getElementById("saasShell")?.classList.remove("sidebar-open")}
function go(n){if(n===7 && !isAdmin()){alert("Acesso exclusivo do administrador.");n=1}updateSaaSNav(n);[1,2,3,4,5,6,7].forEach(i=>{const section=document.getElementById("step"+i);const oldStep=document.getElementById("s"+i);if(section) section.classList.toggle("hidden",i!==n);if(oldStep) oldStep.classList.toggle("active",i===n)});if(n===2) renderWeights();if(n===3) renderRepos();if(n===4) renderClosing();if(n===5) renderSummary();if(n===6) renderHistory();if(n===7) renderAdminGeneral()}
function goAdmin(){if(!session||session.role!=="admin"){alert("Área exclusiva do administrador.");go(1);return}go(7)}
