(function(){
"use strict";
const SB_URL="https://xzuyjodfhqblrharnxoa.supabase.co";
const SB_KEY="sb_publishable_uSmHmHXr_0mwX5H4WGFoHg_3kLSSH1O";
const CATEGORIES=["Entradas, saladas e frios","Guarnições e pratos quentes","Proteínas","Sobremesas","Outros"];
let sharedDishes=[];
const legacyBuildMenu=window.buildMenu;
function normalizeName(v){return String(v||"").trim().replace(/\s+/g," ").toLocaleLowerCase("pt-BR")}
function h(v){return typeof window.esc==="function"?window.esc(v):String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function getSharedDishes(){return sharedDishes.slice()}
window.getSharedDishes=getSharedDishes;
window.buildMenu=function(){const m=typeof legacyBuildMenu==="function"?legacyBuildMenu():{};sharedDishes.forEach(d=>{const cat=CATEGORIES.includes(d.category)?d.category:"Outros";if(!m[cat])m[cat]=[];if(!m[cat].some(n=>normalizeName(n)===normalizeName(d.name)))m[cat].push(d.name)});return m};
async function api(path,{method="GET",body=null}={}){const headers={apikey:SB_KEY};if(body!==null)headers["Content-Type"]="application/json";headers.Prefer="return=representation";const res=await fetch(SB_URL+path,{method,headers,body:body===null?undefined:JSON.stringify(body)});let data=null;const text=await res.text();if(text){try{data=JSON.parse(text)}catch(_){data=text}}if(!res.ok){const err=new Error((data&&data.message)||(data&&data.error_description)||(data&&data.error)||`Erro ${res.status}`);err.status=res.status;err.code=data&&data.code;err.details=data;throw err}return data}
async function loadSharedDishes(){try{const rows=await api("/rest/v1/dishes?select=id,name,category,default_weight,observation,created_at,updated_at&order=category.asc,name.asc");sharedDishes=Array.isArray(rows)?rows:[];if(state&&typeof window.renderMenu==="function")window.renderMenu();const adminSection=document.getElementById("step7");if(adminSection&&!adminSection.classList.contains("hidden")&&typeof window.renderCatalogAdmin==="function")window.renderCatalogAdmin()}catch(e){console.error("Falha ao carregar catálogo compartilhado",e);const msg=document.getElementById("quickDishMsg");if(msg){msg.style.color="var(--red)";msg.textContent="Não foi possível conectar ao catálogo compartilhado agora."}}return sharedDishes}
window.loadSharedDishes=loadSharedDishes;
function dishExists(name,excludeId=null){const key=normalizeName(name);const menu=window.buildMenu();const menuMatch=Object.values(menu).flat().some(n=>normalizeName(n)===key);if(!excludeId)return menuMatch;const otherShared=sharedDishes.some(d=>String(d.id)!==String(excludeId)&&normalizeName(d.name)===key);const baseOrLocal=Object.values(typeof legacyBuildMenu==="function"?legacyBuildMenu():{}).flat().some(n=>normalizeName(n)===key);return otherShared||baseOrLocal}
async function createSharedDish(payload){const rows=await api("/rest/v1/dishes",{method:"POST",body:payload});await loadSharedDishes();return Array.isArray(rows)?rows[0]:rows}
async function updateSharedDish(id,payload){const rows=await api(`/rest/v1/dishes?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:payload});await loadSharedDishes();return Array.isArray(rows)?rows[0]:rows}
async function deleteSharedDish(id){await api(`/rest/v1/dishes?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"});await loadSharedDishes()}
function injectQuickDishUI(){if(document.getElementById("quickDishPanel"))return;const categories=document.getElementById("categories");if(!categories)return;const panel=document.createElement("div");panel.id="quickDishPanel";panel.className="quick-dish-panel";panel.innerHTML=`<div class="quick-dish-head"><div><b>Cadastrar um prato que ainda não existe</b><div class="desc">O novo prato fica salvo na base compartilhada e disponível para todos os usuários.</div></div><button id="quickDishToggle" class="btn primary" type="button">Cadastrar Novo Prato</button></div><div id="quickDishForm" class="quick-dish-form hidden"><div class="quick-dish-grid"><div class="field"><label>NOME DO PRATO</label><input id="quickDishName" placeholder="Ex.: Purê de batata" maxlength="120"></div><div class="field"><label>CATEGORIA</label><select id="quickDishCategory">${CATEGORIES.map(c=>`<option>${h(c)}</option>`).join("")}</select></div><div class="field"><label>PESO PADRÃO (KG) — OPCIONAL</label><input id="quickDishWeight" type="number" step="0.001" min="0" inputmode="decimal" placeholder="0,000"></div><div class="field wide"><label>OBSERVAÇÃO — OPCIONAL</label><textarea id="quickDishObservation" placeholder="Informação útil sobre o prato"></textarea></div></div><div class="quick-dish-actions"><button id="quickDishSave" class="btn primary" type="button">Salvar prato</button><button id="quickDishCancel" class="btn" type="button">Cancelar</button><span id="quickDishMsg" class="quick-dish-msg"></span></div></div>`;categories.parentNode.insertBefore(panel,categories);document.getElementById("quickDishToggle").addEventListener("click",()=>document.getElementById("quickDishForm").classList.toggle("hidden"));document.getElementById("quickDishCancel").addEventListener("click",()=>{document.getElementById("quickDishForm").classList.add("hidden");document.getElementById("quickDishMsg").textContent=""});document.getElementById("quickDishSave").addEventListener("click",saveQuickDish);document.getElementById("quickDishName").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();saveQuickDish()}})}
async function saveQuickDish(){const nameEl=document.getElementById("quickDishName"),catEl=document.getElementById("quickDishCategory"),weightEl=document.getElementById("quickDishWeight"),obsEl=document.getElementById("quickDishObservation"),msg=document.getElementById("quickDishMsg"),btn=document.getElementById("quickDishSave");const name=String(nameEl?.value||"").trim().replace(/\s+/g," ");const category=String(catEl?.value||"Outros");const weightRaw=String(weightEl?.value||"").trim();const default_weight=weightRaw===""?null:Number(weightRaw);const observation=String(obsEl?.value||"").trim()||null;msg.style.color="var(--red)";if(!name){msg.textContent="Informe o nome do prato.";nameEl?.focus();return}if(default_weight!==null&&(!Number.isFinite(default_weight)||default_weight<0)){msg.textContent="Informe um peso padrão válido.";weightEl?.focus();return}if(dishExists(name)){msg.textContent="Este prato já está cadastrado.";return}btn.disabled=true;msg.textContent="Salvando...";try{const created=await createSharedDish({name,category,default_weight,observation});const finalName=created?.name||name;if(state){if(!state.selected.includes(finalName))state.selected.push(finalName);if(typeof window.ensureItemOn==="function")window.ensureItemOn(finalName);if(typeof window.saveDay==="function")window.saveDay()}if(nameEl)nameEl.value="";if(weightEl)weightEl.value="";if(obsEl)obsEl.value="";msg.style.color="var(--green)";msg.textContent="Prato cadastrado com sucesso.";if(typeof window.renderMenu==="function")window.renderMenu()}catch(e){msg.style.color="var(--red)";msg.textContent=(e.code==="23505"||e.status===409)?"Este prato já está cadastrado.":"Não foi possível cadastrar o prato. Tente novamente.";console.error(e)}finally{btn.disabled=false}}
function injectAdminFields(){const form=document.querySelector("#step7 .admin-catalog-form:not(.tray)");if(!form||document.getElementById("catalogDishWeight"))return;const addBtn=document.getElementById("catalogDishAddBtn");if(!addBtn)return;const weightWrap=document.createElement("div");weightWrap.className="field";weightWrap.style.margin="0";weightWrap.innerHTML='<label>PESO PADRÃO (KG) — OPCIONAL</label><input id="catalogDishWeight" type="number" step="0.001" min="0" inputmode="decimal" placeholder="0,000">';const obsWrap=document.createElement("div");obsWrap.className="field";obsWrap.style.margin="0";obsWrap.innerHTML='<label>OBSERVAÇÃO — OPCIONAL</label><textarea id="catalogDishObservation" placeholder="Observação sobre o prato"></textarea>';form.insertBefore(weightWrap,addBtn);form.insertBefore(obsWrap,addBtn);const clone=addBtn.cloneNode(true);addBtn.replaceWith(clone);clone.addEventListener("click",addCatalogDishShared)}
async function addCatalogDishShared(){if(!(session&&session.role==="admin"))return;const nameEl=document.getElementById("catalogDishName"),catEl=document.getElementById("catalogDishCategory"),weightEl=document.getElementById("catalogDishWeight"),obsEl=document.getElementById("catalogDishObservation"),msg=document.getElementById("catalogDishMsg"),btn=document.getElementById("catalogDishAddBtn");const name=String(nameEl?.value||"").trim().replace(/\s+/g," "),category=String(catEl?.value||"Outros"),weightRaw=String(weightEl?.value||"").trim(),default_weight=weightRaw===""?null:Number(weightRaw),observation=String(obsEl?.value||"").trim()||null;msg.style.color="var(--red)";if(!name){msg.textContent="Informe o nome do prato.";return}if(default_weight!==null&&(!Number.isFinite(default_weight)||default_weight<0)){msg.textContent="Informe um peso padrão válido.";return}if(dishExists(name)){msg.textContent="Este prato já está cadastrado.";return}btn.disabled=true;msg.textContent="Salvando...";try{await createSharedDish({name,category,default_weight,observation});nameEl.value="";weightEl.value="";obsEl.value="";msg.style.color="var(--green)";msg.textContent="Prato cadastrado com sucesso.";window.renderCatalogAdmin()}catch(e){msg.style.color="var(--red)";msg.textContent=(e.code==="23505"||e.status===409)?"Este prato já está cadastrado.":"Não foi possível cadastrar o prato.";console.error(e)}finally{btn.disabled=false}}
const legacyRenderCatalogAdmin=window.renderCatalogAdmin;
window.renderCatalogAdmin=function(){if(!(session&&session.role==="admin"))return;injectAdminFields();const dishList=document.getElementById("catalogDishList");if(dishList){const local=typeof window.getAdminDishes==="function"?window.getAdminDishes():[];const sharedHtml=sharedDishes.map(d=>`<div class="admin-catalog-row"><div><b>${h(d.name)}</b><span class="catalog-source">Compartilhado</span><div class="catalog-meta">${d.default_weight===null||d.default_weight===undefined?"Sem peso padrão":Number(d.default_weight).toFixed(3)+" kg"}${d.observation?" • "+h(d.observation):""}</div></div><span>${h(d.category||"Outros")}</span><div class="admin-catalog-actions"><button class="btn small" type="button" onclick="editSharedDish(${Number(d.id)})">Editar</button><button class="btn small danger" type="button" onclick="removeSharedDish(${Number(d.id)})">Excluir</button></div></div>`).join("");const localHtml=local.map((d,i)=>`<div class="admin-catalog-row"><div><b>${h(d.name)}</b><span class="catalog-source">Local antigo</span></div><span>${h(d.category||"Outros")}</span><div class="admin-catalog-actions"><button class="btn small danger" type="button" onclick="removeLocalDish(${i})">Excluir</button></div></div>`).join("");dishList.innerHTML=(sharedHtml+localHtml)||'<div class="desc">Nenhum prato adicional cadastrado.</div>'}const trayList=document.getElementById("catalogTrayList");if(trayList&&typeof legacyRenderCatalogAdmin==="function"){const savedDishHtml=dishList?dishList.innerHTML:null;legacyRenderCatalogAdmin();if(dishList&&savedDishHtml!==null)dishList.innerHTML=savedDishHtml}};
window.editSharedDish=async function(id){if(!(session&&session.role==="admin"))return;const d=sharedDishes.find(x=>String(x.id)===String(id));if(!d)return;const name=prompt("Nome do prato:",d.name);if(name===null)return;const clean=String(name).trim().replace(/\s+/g," ");if(!clean){alert("Informe o nome do prato.");return}if(dishExists(clean,id)){alert("Este prato já está cadastrado.");return}const categoryInput=prompt("Categoria do prato:",d.category||"Outros");if(categoryInput===null)return;const category=CATEGORIES.includes(String(categoryInput).trim())?String(categoryInput).trim():"Outros";const weightInput=prompt("Peso padrão em kg (deixe vazio se não houver):",d.default_weight??"");if(weightInput===null)return;const default_weight=String(weightInput).trim()===""?null:Number(String(weightInput).replace(",","."));if(default_weight!==null&&(!Number.isFinite(default_weight)||default_weight<0)){alert("Peso padrão inválido.");return}const observation=prompt("Observação (opcional):",d.observation||"");if(observation===null)return;try{await updateSharedDish(id,{name:clean,category,default_weight,observation:String(observation).trim()||null});if(state&&d.name!==clean){const pos=state.selected.indexOf(d.name);if(pos>=0)state.selected[pos]=clean;if(state.items&&state.items[d.name]){state.items[clean]=state.items[d.name];delete state.items[d.name]}if(typeof window.saveDay==="function")window.saveDay()}alert("Prato atualizado com sucesso.");if(typeof window.renderMenu==="function")window.renderMenu();window.renderCatalogAdmin()}catch(e){alert((e.code==="23505"||e.status===409)?"Este prato já está cadastrado.":e.message||"Não foi possível atualizar o prato.");console.error(e)}};
window.removeSharedDish=async function(id){if(!(session&&session.role==="admin"))return;const d=sharedDishes.find(x=>String(x.id)===String(id));if(!d)return;if(!confirm(`Excluir o prato "${d.name}" do cadastro compartilhado?`))return;try{await deleteSharedDish(id);window.renderCatalogAdmin();if(typeof window.renderMenu==="function")window.renderMenu();alert("Prato excluído com sucesso.")}catch(e){alert(e.message||"Não foi possível excluir o prato.");console.error(e)}};
window.removeLocalDish=function(index){if(!(session&&session.role==="admin"))return;const list=typeof window.getAdminDishes==="function"?window.getAdminDishes():[];if(index<0||index>=list.length)return;if(!confirm(`Excluir o prato "${list[index].name}" do cadastro local?`))return;list.splice(index,1);if(typeof window.setAdminDishes==="function")window.setAdminDishes(list);window.renderCatalogAdmin();if(typeof window.renderMenu==="function")window.renderMenu()};
injectQuickDishUI();injectAdminFields();loadSharedDishes();
})();
